# Generated by Django 4.2.3 on 2024-05-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jewellery_items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sl", models.CharField(max_length=400)),
                ("itemCode", models.CharField(max_length=500, unique=True)),
                ("article", models.CharField(max_length=500)),
                ("goldType", models.CharField(max_length=500)),
                ("stoneName1", models.CharField(max_length=500)),
                ("stoneName2", models.CharField(max_length=500, null=True)),
                ("stoneName3", models.CharField(max_length=500, null=True)),
                ("stoneName4", models.CharField(max_length=500, null=True)),
                ("description", models.CharField(max_length=50000)),
                ("sellingPriceAED", models.CharField(max_length=500)),
                ("image", models.ImageField(null=True, upload_to="images/")),
            ],
        ),
    ]
