# Generated by Django 4.2.3 on 2024-05-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelleryapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewellery_items",
            name="stoneName2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="jewellery_items",
            name="stoneName3",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="jewellery_items",
            name="stoneName4",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
